force-app/main/default/objects/Product2/fields/GTIN__c.field-meta.xml
<CustomField>
    <fullName>GTIN__c</fullName>
    <description>Product GTIN, 13 digits and unique external id</description>
    <externalId>true</externalId>
    <label>GTIN</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Purchasing_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchasing_Price__c</fullName>
    <description>Product Purchasing Price</description>
    <label>Purchasing Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <description>Product Selling Price</description>
    <label>Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Staging_Product__c/Staging_Product__c.object-meta.xml
<CustomObject>
    <description>Staging Product object to be propagated to Product object</description>
    <label>Staging Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staging_Product__c/fields/GTIN__c.field-meta.xml
<CustomField>
    <fullName>GTIN__c</fullName>
    <description>Product GTIN, 13 digits and unique external id</description>
    <externalId>true</externalId>
    <label>GTIN</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Staging_Product__c/fields/Purchasing_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchasing_Price__c</fullName>
    <description>Price paid by Picnic to suppliers</description>
    <label>Purchasing Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Staging_Product__c/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <description>Price charged by Picnic to consumers</description>
    <label>Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/StagingProductTriggerHandler.cls
/**
 * Staging Product Trigger Handler
 */
public with sharing class StagingProductTriggerHandler {

    public static void propagateStagingProducts(List<Staging_Product__c> newStagingProducts) {

        List<Product2> productsToUpsert = new List<Product2>();
        for (Staging_Product__c sp : newStagingProducts) {
            Product2 product = new Product2(
                GTIN__c = sp.GTIN__c,
                Name = sp.Name,
                Purchasing_Price__c = sp.Purchasing_Price__c,
                Selling_Price__c = sp.Selling_Price__c
            );
            productsToUpsert.add(product);
        }
        try {
            Database.upsert(productsToUpsert, Product2.GTIN__c);
        } catch (DmlException e) {
            // Todo: Options of Error Handling
            // Save logs to custom log object
            // Use SaveResult if partial success
            // Send notifications
        }
        // Todo: if user manually update price on product, should overwrite or not?

    }
}