force-app/main/default/objects/Product2/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <description>Product Selling Price</description>
    <label>Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Selling_Price_Before__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price_Before__c</fullName>
    <description>The previous selling price when updated</description>
    <label>Selling Price Before</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProductTriggerHandler.cls
/**
 * Product Trigger Handler
 */
public with sharing class ProductTriggerHandler {

    public static void updateSellingPriceBefore(List<Product2> newProducts, Map<Id, Product2> oldProductsMap) {

        for (Product2 p : newProducts) {
            if (oldProductsMap.get(p.Id).Selling_Price__c != p.Selling_Price__c) {
                p.Selling_Price_Before__c = oldProductsMap.get(p.Id).Selling_Price__c;
            }
        }

    }

}